import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '@/utils/trpc';
import PokemonListing from '@/components/PokemonListing';
import { usePlausible } from 'next-plausible';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
  const {
    data: pokemonPair,
    refetch,
    isLoading,
  } = trpc.useQuery(['get-pokemon-pair'], {
    refetchInterval: false,
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
  });

  const voteMutation = trpc.useMutation(['cast-vote']);
  const plausible = usePlausible();

  const voteForRoundest = (selected: number) => {
    if (!pokemonPair) return;

    if (selected === pokemonPair?.firstPokemon.id) {
      voteMutation.mutate({
        votedFor: pokemonPair.firstPokemon.id,
        votedAgainst: pokemonPair.secondPokemon.id,
      });
    } else {
      voteMutation.mutate({
        votedFor: pokemonPair.secondPokemon.id,
        votedAgainst: pokemonPair.firstPokemon.id,
      });
    }

    refetch();
  };

  const fetchingNext = voteMutation.isLoading || isLoading;

  return (
    <div>
      <Head>
        <title>Roundest Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-creen flex flex-col justify-center items-center relative">
        {pokemonPair && (
          <div className="p-8 flex justify-between items-center max-w-2xl flex-col md:flex-row animate-fade-in">
            <PokemonListing
              pokemon={pokemonPair.firstPokemon}
              vote={() => voteForRoundest(pokemonPair.firstPokemon.id)}
              disabled={fetchingNext}
            />
            <div className="p-8 italic text-xl">{'or'}</div>
            <PokemonListing
              pokemon={pokemonPair.secondPokemon}
              vote={() => voteForRoundest(pokemonPair.secondPokemon.id)}
              disabled={fetchingNext}
            />
            <div className="p-2" />
          </div>
        )}
        {!pokemonPair && (
          <Image
            src="/three-dots.svg"
            layout="fill"
            className="w-48"
            alt="loading animation"
          />
        )}
        <div className="mt-5">
          <Link href="/results" passHref>
            <a>
              <button className="inline-flex items-center px-3 py-1.5 shadow-sm font-medium rounded-full text-gray-700 bg-red-400 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                See results
              </button>
            </a>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
